parameters:
#    random_hello.example.class: Random\HelloBundle\Example

services:
#    random_hello.example:
#        class: %random_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
